
services:
  server:
    build: server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - exclude_venv:/app/venv
  client:
    build: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - exclude_node_modules:/app/node_modules

volumes:
  exclude_venv:
  exclude_node_modules: